version: "3"
services:

    frontend:
        command: serve -s build -l 3000
        container_name: space-frontend
        restart: unless-stopped
        build:
            context: ./frontend
            dockerfile: Dockerfile.live

    nginx:
        image: nginx:stable-alpine
        container_name: space-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./api/:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - frontend
            - php

    mysql:
        image: percona
        container_name: space-mysql
        restart: unless-stopped
        command: --max_allowed_packet=16M
        environment:
            MYSQL_ROOT_PASSWORD: spaceroot
            MYSQL_DATABASE: space
            MYSQL_USER: spaceuser
            MYSQL_PASSWORD: spacepass

    php:
        container_name: space-php
        restart: unless-stopped
        build: api/docker/php
        links:
            - mysql
        volumes:
            - ./api:/var/www/html
        depends_on:
            - mysql