version: "3"
services:

    frontend:
        command: npm run start
        container_name: space-frontend
        build: frontend
        ports:
            - "3000:3000"
        tty: true
        stdin_open: true
        volumes:
            - ./frontend/src:/usr/src/app/src

    nginx:
        image: nginx:stable-alpine
        container_name: space-nginx
        ports:
            - "80:80"
        volumes:
            - ./api/:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/nginx.conf
        depends_on:
            - frontend
            - php

    mysql:
        image: percona
        restart: always
        container_name: space-mysql
        ports:
            - 3307:3306
        command: --max_allowed_packet=16M
        environment:
            MYSQL_ROOT_PASSWORD: spaceroot
            MYSQL_DATABASE: space
            MYSQL_USER: spaceuser
            MYSQL_PASSWORD: spacepass

    php:
        container_name: space-php
        build: api/docker/php
        links:
            - mysql
        volumes:
            - ./api:/var/www/html
        depends_on:
            - mysql