version: '3'
services:

  mysql:
    image: percona
    restart: always
    container_name: space-mysql
    ports:
      - 3307:3306
    command: --max_allowed_packet=16M
    environment:
      MYSQL_ROOT_PASSWORD: spaceroot
      MYSQL_DATABASE: space
      MYSQL_USER: spaceuser
      MYSQL_PASSWORD: spacepass

  php:
    container_name: space-php
    build: docker/php
    links:
      - mysql
    volumes:
      - ./:/var/www/html
      - ./docker/php/config:/usr/local/etc/php/
    depends_on:
      - mysql

  nginx:
    container_name: space-nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      default:
        aliases:
          - space.loc
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
